### PR TITLE
New Version #1: Edits to Introductions

### PR DESCRIPTION
**Pull request by charlesfrye**
I re-worked the introduction sections: Positive-Only Sparse Coding, Mathematical Interpretation, and Neural Interpretation. They move more slowly and repeat themselves. Repeating yourself makes sure people understand why you've done something, even though you move more slowly. 

I also refactored some of the code so that, e.g., the error function is always referred to as such.

You'll notice some rather ebullient use of Markdown, a couple of discussion-type questions, and a few tangents, mostly relegated to footnotes. If you're unsure of the purpose of any of these pieces,
just let me know so we can make sure we're all on the same page as teachers.

I also switched all the color maps for displaying the digits to 'gray_r' instead of 'gray', so that the digits would be black on white.

Later, I plan to pull request a version with the natural images dataset as well. I just wanted to get the ball rolling on these changes, since I might not get to the others until pretty late tonight.

### CODE REVIEW

**Comment by alexanderganderson** [comment]
Hey,

Thanks for expanding on the notebook and making these changes. Two small things, I think it would make more sense to leave the sparsity penalty as sum |A|, instead of simplifying it in the case of the coefficients being positive.  Two, anaconda defaults to install python 2, so it should be 
print 'blah' 
instead of
print('blah')

I'll merge after those changes are made.

**Comment by alexanderganderson** [comment]
Also can you change the energy function to be
|i-da|^2 + lambda \* |a|    and then define lambda as the tradeoff between sparsity and reconstruction error.

**Comment by charlesfrye** [comment]
The problem with including the absolute value there is that we've introduced "Positive-Only Sparse Coding" already. I also explained why we chose to use that constraint, in the previous section. It's somewhat confusing if we then give the vanilla Sparse Coding error function.

I'm not super familiar with the positive-only flavor, so I don't know if there's any inaccuracies. If so, I agree we should either fix them or just use the original error function. If we go back to the vanilla error function, then we should also re-organize the notebook so that the positive-only constraint doesn't come up until after the section on the math.

The functional print works in my 2.7 environment and with the tmpnb Python 2 image. Does it not work for you? I'm hoping to have the whole notebook 3-ready by tomorrow, in case anyone has their own install.

I will add in lambda.

**Comment by alexanderganderson** [comment]
I don't think that it is that confusing to have an extra absolute value in
there.  Also if you are doing the images example, it would be easier to
have the same objective function for both.

Also I think that it would be better to use the word 'cost function' or
'objective function' rather than 'error function' (I haven't heard 'error
function' used in this context before').

The positive only is basically the same algorithm, just we restrict things
to be positive when we do the minimization.

**Comment by JesseLivezey** [comment]
@alexanderganderson, `print('blah')` should work on on python 2 or 3.

**Comment by JesseLivezey** [comment]
Also just noticed that github doesn't seem to render the html markdown. All of the discussion questions are missing. :(

**Comment by JesseLivezey** [comment]
You also have a dangling parenthesis: "(look at the wavelets. They're incredibly similar!"

**Comment by charlesfrye** [comment]
@JesseLivezey fixed ) and checked out the missing questions. Can you confirm they're still there in the notebook when run on your home machine?

**Comment by charlesfrye** [comment]
@alexanderganderson 

I'll change everything to "cost" instead of "error".

I'd really rather not introduce multiple cost functions. Besides using the natural images dataset, what is the reason for showing the original?

**Comment by alexanderganderson** [comment]
For natural images, the sparse coefficients can be positive or negative, so
it would make sense to just use |A| for both and if somebody asks about
that being redundant, we can just explain that. I don't care that much, and
I'll trust you to make a reasonable decision on this.

On Mon, Aug 24, 2015 at 7:12 PM, Charles Frye notifications@github.com
wrote:

> I'll change everything to "cost" instead of "error".
> 
> I'd really rather not introduce multiple cost functions. Besides using the
> natural images dataset, what is the reason for showing the original?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rctn/RCTN-neuro-bootcamp/pull/1#issuecomment-134449657
> .

## 

Alex Anderson
Graduate Student in the Redwood Center for Theoretical Neuroscience
Evans Hall 559
Olshausen Research Group

University of California, Berkeley
aga@berkeley.edu | LinkedIn http://www.linkedin.com/in/alexanderganderson
 | Personal Site http://www.ocf.berkeley.edu/~aga/

**Comment by charlesfrye** [comment]
Alright, I've implemented all of the things we discussed, save putting the absolute value back. I'm going to pull the trigger on the merge and get to work on the natural images example.

**Pull request merged**
